name: Sentinel CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas joblib scikit-learn flask prometheus_client
        # Agar aapki requirements.txt file hai toh: pip install -r requirements.txt

    - name: Build Docker Image
      run: |
        docker build -t sentinel-webapp .
        echo "Docker Image built successfully!"

    - name: Final Status
      run: echo "CI/CD Pipeline passed. Code is ready for deployment!"